# 动物数据库 - 包含分类、数据、科普知识等（每类至少12种）

ANIMAL_CATEGORIES = {
    "mammals": {
        "name": {"en": "Mammals", "zh": "哺乳动物", "ko": "포유류"},
        "icon": "fa-paw",
        "description": {
            "en": "Warm-blooded vertebrates that usually give live birth and nurse their young.",
            "zh": "温血、胎生、哺乳的脊椎动物。",
            "ko": "대부분 새끼를 낳아 젖을 먹이는 온혈 척추동물.",
        },
        "count": 5500,
    },
    "birds": {
        "name": {"en": "Birds", "zh": "鸟类", "ko": "조류"},
        "icon": "fa-dove",
        "description": {
            "en": "Feathered, warm-blooded animals; many are adapted for flight.",
            "zh": "有羽毛、能飞行的温血动物。",
            "ko": "깃털을 가진 온혈 동물로, 많은 종이 비행에 적응.",
        },
        "count": 10000,
    },
    "reptiles": {
        "name": {"en": "Reptiles", "zh": "爬行动物", "ko": "파충류"},
        "icon": "fa-dragon",
        "description": {
            "en": "Cold-blooded vertebrates with scales; most lay eggs.",
            "zh": "冷血、有鳞片的卵生动物。",
            "ko": "비늘이 있는 변온 척추동물로 대부분 알을 낳음.",
        },
        "count": 10000,
    },
    "amphibians": {
        "name": {"en": "Amphibians", "zh": "两栖动物", "ko": "양서류"},
        "icon": "fa-frog",
        "description": {
            "en": "Animals that often live both in water and on land with metamorphosis.",
            "zh": "水陆两栖、变态发育的动物。",
            "ko": "물과 육지에서 살며 변태 과정을 거치는 동물.",
        },
        "count": 7000,
    },
    "fish": {
        "name": {"en": "Fish", "zh": "鱼类", "ko": "어류"},
        "icon": "fa-fish",
        "description": {
            "en": "Aquatic vertebrates that breathe mainly with gills.",
            "zh": "水生、用鳃呼吸的脊椎动物。",
            "ko": "대부분 아가미로 호흡하는 수생 척추동물.",
        },
        "count": 32000,
    },
    "insects": {
        "name": {"en": "Insects", "zh": "昆虫", "ko": "곤충"},
        "icon": "fa-bug",
        "description": {
            "en": "Six-legged arthropods with exoskeletons; the most diverse animal group.",
            "zh": "六足、有外骨骼的节肢动物。",
            "ko": "외골격을 가진 6개의 다리를 지닌 절지동물.",
        },
        "count": 1000000,
    },
}


# 为了保持文件可读性，每个动物条目字段尽量统一
# name/description/habitat/distribution 使用多语言 dict
ANIMALS_DATA = {
    # ---------------- Mammals (12) ----------------
    "giant_panda": {
        "name": {"en": "Giant Panda", "zh": "大熊猫", "ko": "자이언트 판다"},
        "category": "mammals",
        "scientific_name": "Ailuropoda melanoleuca",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1558980664-10ea9c9c4a34?w=1200",
        "description": {
            "en": "A bamboo-specialist bear native to China, famous for its black-and-white coat.",
            "zh": "中国特有的竹食性熊类，以黑白相间外貌闻名。",
            "ko": "중국 고유의 대나무를 주로 먹는 곰으로 흑백 털이 특징.",
        },
        "characteristics": [
            "Strong jaws adapted for bamboo",
            "Pseudo-thumb helps grasp stalks",
        ],
        "habitat": {
            "en": "Temperate mountain forests with dense bamboo",
            "zh": "温带山地竹林森林",
            "ko": "대나무가 풍부한 온대 산림",
        },
        "distribution": {
            "en": "Sichuan, Shaanxi, Gansu (China)",
            "zh": "中国四川、陕西、甘肃",
            "ko": "중국 쓰촨, 산시, 간쑤",
        },
        "facts": [
            "Spends most of the day eating.",
            "Newborns are extremely small compared to adults.",
        ],
    },
    "tiger": {
        "name": {"en": "Tiger", "zh": "老虎", "ko": "호랑이"},
        "category": "mammals",
        "scientific_name": "Panthera tigris",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200",
        "description": {
            "en": "The largest cat species, known for its powerful build and striped coat.",
            "zh": "现存最大的猫科动物，以强大力量和条纹皮毛著称。",
            "ko": "현존하는 가장 큰 고양잇과 동물로 줄무늬 털이 특징.",
        },
        "characteristics": ["Solitary hunter", "Unique stripe patterns"],
        "habitat": {
            "en": "Forests, grasslands, mangroves",
            "zh": "森林、草原、红树林",
            "ko": "숲, 초원, 맹그로브",
        },
        "distribution": {
            "en": "South & East Asia, Russian Far East",
            "zh": "南亚、东亚及俄罗斯远东",
            "ko": "남·동아시아 및 러시아 극동",
        },
        "facts": ["Excellent night vision", "Apex predator"],
    },
    "african_elephant": {
        "name": {"en": "African Elephant", "zh": "非洲象", "ko": "아프리카 코끼리"},
        "category": "mammals",
        "scientific_name": "Loxodonta africana",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=1200",
        "description": {
            "en": "The largest land mammal, highly intelligent and social.",
            "zh": "陆地上体型最大的哺乳动物，聪明且社会性强。",
            "ko": "가장 큰 육상 포유류로 지능과 사회성이 뛰어남.",
        },
        "characteristics": ["Long trunk", "Large ears help cooling"],
        "habitat": {"en": "Savannas and forests", "zh": "草原与森林", "ko": "사바나와 숲"},
        "distribution": {
            "en": "Sub-Saharan Africa",
            "zh": "撒哈拉以南非洲",
            "ko": "사하라 이남 아프리카",
        },
        "facts": ["Pregnancy lasts ~22 months", "Uses infrasound to communicate"],
    },
    "gray_wolf": {
        "name": {"en": "Gray Wolf", "zh": "灰狼", "ko": "회색늑대"},
        "category": "mammals",
        "scientific_name": "Canis lupus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=1200",
        "description": {
            "en": "A social canid forming packs with complex communication.",
            "zh": "具有复杂社会结构的犬科动物，常以狼群形式生活。",
            "ko": "복잡한 사회 구조를 가진 무리 생활의 개과 동물.",
        },
        "characteristics": ["Pack hunting", "Wide vocal range"],
        "habitat": {"en": "Forests, tundra, grasslands", "zh": "森林、苔原、草原", "ko": "숲, 툰드라, 초원"},
        "distribution": {"en": "North America, Europe, Asia", "zh": "北美、欧洲、亚洲", "ko": "북미, 유럽, 아시아"},
        "facts": ["Key apex predator in many ecosystems"],
    },
    "polar_bear": {
        "name": {"en": "Polar Bear", "zh": "北极熊", "ko": "북극곰"},
        "category": "mammals",
        "scientific_name": "Ursus maritimus",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1546182990-7f8b7b54b1b4?w=1200",
        "description": {
            "en": "A sea-ice specialist bear, superb swimmer.",
            "zh": "依赖海冰生存的熊类，游泳能力极强。",
            "ko": "해빙에 의존하는 곰으로 수영 능력이 뛰어남.",
        },
        "characteristics": ["Thick blubber", "White fur for camouflage"],
        "habitat": {"en": "Arctic sea ice", "zh": "北极海冰区", "ko": "북극 해빙"},
        "distribution": {"en": "Arctic Circle", "zh": "北极圈周边", "ko": "북극권"},
        "facts": ["Climate change is a major threat"],
    },
    "red_fox": {
        "name": {"en": "Red Fox", "zh": "赤狐", "ko": "붉은여우"},
        "category": "mammals",
        "scientific_name": "Vulpes vulpes",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1465156799763-2c087c332922?w=1200",
        "description": {
            "en": "An adaptable canid found even in urban areas.",
            "zh": "适应能力极强的犬科动物，甚至能在城市生存。",
            "ko": "도시에서도 살아가는 적응력이 뛰어난 개과 동물.",
        },
        "characteristics": ["Omnivorous", "Excellent hearing"],
        "habitat": {"en": "Forests, grasslands, cities", "zh": "森林、草原、城市", "ko": "숲, 초원, 도시"},
        "distribution": {"en": "Northern Hemisphere", "zh": "北半球广泛分布", "ko": "북반구"},
        "facts": ["Uses Earth's magnetic field to hunt"],
    },
    "kangaroo": {
        "name": {"en": "Red Kangaroo", "zh": "红大袋鼠", "ko": "붉은캥거루"},
        "category": "mammals",
        "scientific_name": "Osphranter rufus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        "description": {
            "en": "Australia’s largest marsupial, famous for powerful hopping.",
            "zh": "澳大利亚最大的有袋类动物，以强劲跳跃能力著称。",
            "ko": "호주의 가장 큰 유대류로 강력한 점프가 특징.",
        },
        "characteristics": ["Strong hind legs", "Pouch for young"],
        "habitat": {"en": "Arid and semi-arid plains", "zh": "干旱与半干旱平原", "ko": "건조·반건조 평원"},
        "distribution": {"en": "Australia", "zh": "澳大利亚", "ko": "호주"},
        "facts": ["Can travel long distances efficiently by hopping"],
    },
    "bottlenose_dolphin": {
        "name": {"en": "Bottlenose Dolphin", "zh": "宽吻海豚", "ko": "큰돌고래"},
        "category": "mammals",
        "scientific_name": "Tursiops truncatus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        "description": {
            "en": "Highly intelligent marine mammal using echolocation.",
            "zh": "高度聪明的海洋哺乳动物，擅长回声定位。",
            "ko": "반향정위를 사용하는 지능 높은 해양 포유류.",
        },
        "characteristics": ["Echolocation", "Complex social groups"],
        "habitat": {"en": "Coastal and offshore waters", "zh": "近海及外海", "ko": "연안 및 외해"},
        "distribution": {"en": "Worldwide in temperate/tropical seas", "zh": "全球温带与热带海域", "ko": "전 세계 온·열대 해역"},
        "facts": ["Can recognize themselves in mirrors (evidence of self-awareness)"],
    },
    "blue_whale": {
        "name": {"en": "Blue Whale", "zh": "蓝鲸", "ko": "대왕고래"},
        "category": "mammals",
        "scientific_name": "Balaenoptera musculus",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1570481662006-a3a1374699e8?w=1200",
        "description": {
            "en": "The largest animal known to have ever lived.",
            "zh": "已知地球历史上最大的动物。",
            "ko": "지구 역사상 가장 큰 동물로 알려짐.",
        },
        "characteristics": ["Feeds mainly on krill", "Massive heart"],
        "habitat": {"en": "Open oceans", "zh": "远洋", "ko": "대양"},
        "distribution": {"en": "All major oceans", "zh": "世界各大洋", "ko": "전 세계 대양"},
        "facts": ["A single call can travel hundreds of kilometers"],
    },
    "koala": {
        "name": {"en": "Koala", "zh": "考拉", "ko": "코알라"},
        "category": "mammals",
        "scientific_name": "Phascolarctos cinereus",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?w=1200",
        "description": {
            "en": "An arboreal marsupial that feeds on eucalyptus leaves.",
            "zh": "树栖有袋类动物，以桉树叶为食。",
            "ko": "유칼립투스 잎을 먹는 나무 위 생활의 유대류.",
        },
        "characteristics": ["Low-energy lifestyle", "Strong claws"],
        "habitat": {"en": "Eucalyptus forests", "zh": "桉树林", "ko": "유칼립투스 숲"},
        "distribution": {"en": "Eastern Australia", "zh": "澳大利亚东部", "ko": "호주 동부"},
        "facts": ["Sleeps up to ~20 hours a day"],
    },
    "snow_leopard": {
        "name": {"en": "Snow Leopard", "zh": "雪豹", "ko": "설표"},
        "category": "mammals",
        "scientific_name": "Panthera uncia",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1546182990-5f7c0b2c5d50?w=1200",
        "description": {
            "en": "A rare big cat adapted to cold, high mountains.",
            "zh": "适应高寒山地环境的稀有大型猫科动物。",
            "ko": "고산의 추운 환경에 적응한 희귀한 대형 고양잇과.",
        },
        "characteristics": ["Thick fur", "Long tail for balance"],
        "habitat": {"en": "High-altitude alpine regions", "zh": "高海拔山地", "ko": "고지대 산악"},
        "distribution": {"en": "Central and South Asia", "zh": "中亚及南亚", "ko": "중앙·남아시아"},
        "facts": ["Nicknamed 'ghost of the mountains'"],
    },
    "orangutan": {
        "name": {"en": "Orangutan", "zh": "猩猩（红毛猩猩类）", "ko": "오랑우탄"},
        "category": "mammals",
        "scientific_name": "Pongo spp.",
        "conservation_status": "CR",
        "image": "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=1200",
        "description": {
            "en": "Great apes of Borneo and Sumatra, famous for intelligence and arboreal life.",
            "zh": "婆罗洲与苏门答腊的大型人猿，以聪明和树栖生活著称。",
            "ko": "보르네오와 수마트라의 대형 유인원으로 지능이 뛰어남.",
        },
        "characteristics": ["Uses tools", "Very long arm span"],
        "habitat": {"en": "Tropical rainforests", "zh": "热带雨林", "ko": "열대우림"},
        "distribution": {"en": "Borneo, Sumatra", "zh
