# 动物数据库 - 包含分类、数据、科普知识等（每类至少12种）

ANIMAL_CATEGORIES = {
    "mammals": {
        "name": {"en": "Mammals", "zh": "哺乳动物", "ko": "포유류"},
        "icon": "fa-paw",
        "description": {
            "en": "Warm-blooded vertebrates that usually give live birth and nurse their young.",
            "zh": "温血、胎生、哺乳的脊椎动物。",
            "ko": "대부분 새끼를 낳아 젖을 먹이는 온혈 척추동물.",
        },
        "count": 5500,
    },
    "birds": {
        "name": {"en": "Birds", "zh": "鸟类", "ko": "조류"},
        "icon": "fa-dove",
        "description": {
            "en": "Feathered, warm-blooded animals; many are adapted for flight.",
            "zh": "有羽毛、能飞行的温血动物。",
            "ko": "깃털을 가진 온혈 동물로, 많은 종이 비행에 적응.",
        },
        "count": 10000,
    },
    "reptiles": {
        "name": {"en": "Reptiles", "zh": "爬行动物", "ko": "파충류"},
        "icon": "fa-dragon",
        "description": {
            "en": "Cold-blooded vertebrates with scales; most lay eggs.",
            "zh": "冷血、有鳞片的卵生动物。",
            "ko": "비늘이 있는 변온 척추동물로 대부분 알을 낳음.",
        },
        "count": 10000,
    },
    "amphibians": {
        "name": {"en": "Amphibians", "zh": "两栖动物", "ko": "양서류"},
        "icon": "fa-frog",
        "description": {
            "en": "Animals that often live both in water and on land with metamorphosis.",
            "zh": "水陆两栖、变态发育的动物。",
            "ko": "물과 육지에서 살며 변태 과정을 거치는 동물.",
        },
        "count": 7000,
    },
    "fish": {
        "name": {"en": "Fish", "zh": "鱼类", "ko": "어류"},
        "icon": "fa-fish",
        "description": {
            "en": "Aquatic vertebrates that breathe mainly with gills.",
            "zh": "水生、用鳃呼吸的脊椎动物。",
            "ko": "대부분 아가미로 호흡하는 수생 척추동물.",
        },
        "count": 32000,
    },
    "insects": {
        "name": {"en": "Insects", "zh": "昆虫", "ko": "곤충"},
        "icon": "fa-bug",
        "description": {
            "en": "Six-legged arthropods with exoskeletons; the most diverse animal group.",
            "zh": "六足、有外骨骼的节肢动物。",
            "ko": "외골격을 가진 6개의 다리를 지닌 절지동물.",
        },
        "count": 1000000,
    },
}


# 为了保持文件可读性，每个动物条目字段尽量统一
# name/description/habitat/distribution 使用多语言 dict
ANIMALS_DATA = {
    # ---------------- Mammals (12) ----------------
    "giant_panda": {
        "name": {"en": "Giant Panda", "zh": "大熊猫", "ko": "자이언트 판다"},
        "category": "mammals",
        "scientific_name": "Ailuropoda melanoleuca",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1558980664-10ea9c9c4a34?w=1200",
        "description": {
            "en": "A bamboo-specialist bear native to China, famous for its black-and-white coat.",
            "zh": "中国特有的竹食性熊类，以黑白相间外貌闻名。",
            "ko": "중국 고유의 대나무를 주로 먹는 곰으로 흑백 털이 특징.",
        },
        "characteristics": [
            "Strong jaws adapted for bamboo",
            "Pseudo-thumb helps grasp stalks",
        ],
        "habitat": {
            "en": "Temperate mountain forests with dense bamboo",
            "zh": "温带山地竹林森林",
            "ko": "대나무가 풍부한 온대 산림",
        },
        "distribution": {
            "en": "Sichuan, Shaanxi, Gansu (China)",
            "zh": "中国四川、陕西、甘肃",
            "ko": "중국 쓰촨, 산시, 간쑤",
        },
        "facts": [
            "Spends most of the day eating.",
            "Newborns are extremely small compared to adults.",
        ],
    },
    "tiger": {
        "name": {"en": "Tiger", "zh": "老虎", "ko": "호랑이"},
        "category": "mammals",
        "scientific_name": "Panthera tigris",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200",
        "description": {
            "en": "The largest cat species, known for its powerful build and striped coat.",
            "zh": "现存最大的猫科动物，以强大力量和条纹皮毛著称。",
            "ko": "현존하는 가장 큰 고양잇과 동물로 줄무늬 털이 특징.",
        },
        "characteristics": ["Solitary hunter", "Unique stripe patterns"],
        "habitat": {
            "en": "Forests, grasslands, mangroves",
            "zh": "森林、草原、红树林",
            "ko": "숲, 초원, 맹그로브",
        },
        "distribution": {
            "en": "South & East Asia, Russian Far East",
            "zh": "南亚、东亚及俄罗斯远东",
            "ko": "남·동아시아 및 러시아 극동",
        },
        "facts": ["Excellent night vision", "Apex predator"],
    },
    "african_elephant": {
        "name": {"en": "African Elephant", "zh": "非洲象", "ko": "아프리카 코끼리"},
        "category": "mammals",
        "scientific_name": "Loxodonta africana",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=1200",
        "description": {
            "en": "The largest land mammal, highly intelligent and social.",
            "zh": "陆地上体型最大的哺乳动物，聪明且社会性强。",
            "ko": "가장 큰 육상 포유류로 지능과 사회성이 뛰어남.",
        },
        "characteristics": ["Long trunk", "Large ears help cooling"],
        "habitat": {"en": "Savannas and forests", "zh": "草原与森林", "ko": "사바나와 숲"},
        "distribution": {
            "en": "Sub-Saharan Africa",
            "zh": "撒哈拉以南非洲",
            "ko": "사하라 이남 아프리카",
        },
        "facts": ["Pregnancy lasts ~22 months", "Uses infrasound to communicate"],
    },
    "gray_wolf": {
        "name": {"en": "Gray Wolf", "zh": "灰狼", "ko": "회색늑대"},
        "category": "mammals",
        "scientific_name": "Canis lupus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=1200",
        "description": {
            "en": "A social canid forming packs with complex communication.",
            "zh": "具有复杂社会结构的犬科动物，常以狼群形式生活。",
            "ko": "복잡한 사회 구조를 가진 무리 생활의 개과 동물.",
        },
        "characteristics": ["Pack hunting", "Wide vocal range"],
        "habitat": {"en": "Forests, tundra, grasslands", "zh": "森林、苔原、草原", "ko": "숲, 툰드라, 초원"},
        "distribution": {"en": "North America, Europe, Asia", "zh": "北美、欧洲、亚洲", "ko": "북미, 유럽, 아시아"},
        "facts": ["Key apex predator in many ecosystems"],
    },
    "polar_bear": {
        "name": {"en": "Polar Bear", "zh": "北极熊", "ko": "북극곰"},
        "category": "mammals",
        "scientific_name": "Ursus maritimus",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1546182990-7f8b7b54b1b4?w=1200",
        "description": {
            "en": "A sea-ice specialist bear, superb swimmer.",
            "zh": "依赖海冰生存的熊类，游泳能力极强。",
            "ko": "해빙에 의존하는 곰으로 수영 능력이 뛰어남.",
        },
        "characteristics": ["Thick blubber", "White fur for camouflage"],
        "habitat": {"en": "Arctic sea ice", "zh": "北极海冰区", "ko": "북극 해빙"},
        "distribution": {"en": "Arctic Circle", "zh": "北极圈周边", "ko": "북극권"},
        "facts": ["Climate change is a major threat"],
    },
    "red_fox": {
        "name": {"en": "Red Fox", "zh": "赤狐", "ko": "붉은여우"},
        "category": "mammals",
        "scientific_name": "Vulpes vulpes",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1465156799763-2c087c332922?w=1200",
        "description": {
            "en": "An adaptable canid found even in urban areas.",
            "zh": "适应能力极强的犬科动物，甚至能在城市生存。",
            "ko": "도시에서도 살아가는 적응력이 뛰어난 개과 동물.",
        },
        "characteristics": ["Omnivorous", "Excellent hearing"],
        "habitat": {"en": "Forests, grasslands, cities", "zh": "森林、草原、城市", "ko": "숲, 초원, 도시"},
        "distribution": {"en": "Northern Hemisphere", "zh": "北半球广泛分布", "ko": "북반구"},
        "facts": ["Uses Earth's magnetic field to hunt"],
    },
    "kangaroo": {
        "name": {"en": "Red Kangaroo", "zh": "红大袋鼠", "ko": "붉은캥거루"},
        "category": "mammals",
        "scientific_name": "Osphranter rufus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        "description": {
            "en": "Australia’s largest marsupial, famous for powerful hopping.",
            "zh": "澳大利亚最大的有袋类动物，以强劲跳跃能力著称。",
            "ko": "호주의 가장 큰 유대류로 강력한 점프가 특징.",
        },
        "characteristics": ["Strong hind legs", "Pouch for young"],
        "habitat": {"en": "Arid and semi-arid plains", "zh": "干旱与半干旱平原", "ko": "건조·반건조 평원"},
        "distribution": {"en": "Australia", "zh": "澳大利亚", "ko": "호주"},
        "facts": ["Can travel long distances efficiently by hopping"],
    },
    "bottlenose_dolphin": {
        "name": {"en": "Bottlenose Dolphin", "zh": "宽吻海豚", "ko": "큰돌고래"},
        "category": "mammals",
        "scientific_name": "Tursiops truncatus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        "description": {
            "en": "Highly intelligent marine mammal using echolocation.",
            "zh": "高度聪明的海洋哺乳动物，擅长回声定位。",
            "ko": "반향정위를 사용하는 지능 높은 해양 포유류.",
        },
        "characteristics": ["Echolocation", "Complex social groups"],
        "habitat": {"en": "Coastal and offshore waters", "zh": "近海及外海", "ko": "연안 및 외해"},
        "distribution": {"en": "Worldwide in temperate/tropical seas", "zh": "全球温带与热带海域", "ko": "전 세계 온·열대 해역"},
        "facts": ["Can recognize themselves in mirrors (evidence of self-awareness)"],
    },
    "blue_whale": {
        "name": {"en": "Blue Whale", "zh": "蓝鲸", "ko": "대왕고래"},
        "category": "mammals",
        "scientific_name": "Balaenoptera musculus",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1570481662006-a3a1374699e8?w=1200",
        "description": {
            "en": "The largest animal known to have ever lived.",
            "zh": "已知地球历史上最大的动物。",
            "ko": "지구 역사상 가장 큰 동물로 알려짐.",
        },
        "characteristics": ["Feeds mainly on krill", "Massive heart"],
        "habitat": {"en": "Open oceans", "zh": "远洋", "ko": "대양"},
        "distribution": {"en": "All major oceans", "zh": "世界各大洋", "ko": "전 세계 대양"},
        "facts": ["A single call can travel hundreds of kilometers"],
    },
    "koala": {
        "name": {"en": "Koala", "zh": "考拉", "ko": "코알라"},
        "category": "mammals",
        "scientific_name": "Phascolarctos cinereus",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?w=1200",
        "description": {
            "en": "An arboreal marsupial that feeds on eucalyptus leaves.",
            "zh": "树栖有袋类动物，以桉树叶为食。",
            "ko": "유칼립투스 잎을 먹는 나무 위 생활의 유대류.",
        },
        "characteristics": ["Low-energy lifestyle", "Strong claws"],
        "habitat": {"en": "Eucalyptus forests", "zh": "桉树林", "ko": "유칼립투스 숲"},
        "distribution": {"en": "Eastern Australia", "zh": "澳大利亚东部", "ko": "호주 동부"},
        "facts": ["Sleeps up to ~20 hours a day"],
    },
    "snow_leopard": {
        "name": {"en": "Snow Leopard", "zh": "雪豹", "ko": "설표"},
        "category": "mammals",
        "scientific_name": "Panthera uncia",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1546182990-5f7c0b2c5d50?w=1200",
        "description": {
            "en": "A rare big cat adapted to cold, high mountains.",
            "zh": "适应高寒山地环境的稀有大型猫科动物。",
            "ko": "고산의 추운 환경에 적응한 희귀한 대형 고양잇과.",
        },
        "characteristics": ["Thick fur", "Long tail for balance"],
        "habitat": {"en": "High-altitude alpine regions", "zh": "高海拔山地", "ko": "고지대 산악"},
        "distribution": {"en": "Central and South Asia", "zh": "中亚及南亚", "ko": "중앙·남아시아"},
        "facts": ["Nicknamed 'ghost of the mountains'"],
    },
    "orangutan": {
        "name": {"en": "Orangutan", "zh": "猩猩（红毛猩猩类）", "ko": "오랑우탄"},
        "category": "mammals",
        "scientific_name": "Pongo spp.",
        "conservation_status": "CR",
        "image": "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=1200",
        "description": {
            "en": "Great apes of Borneo and Sumatra, famous for intelligence and arboreal life.",
            "zh": "婆罗洲与苏门答腊的大型人猿，以聪明和树栖生活著称。",
            "ko": "보르네오와 수마트라의 대형 유인원으로 지능이 뛰어남.",
        },
        "characteristics": ["Uses tools", "Very long arm span"],
        "habitat": {"en": "Tropical rainforests", "zh": "热带雨林", "ko": "열대우림"},
        "distribution": {"en": "Borneo, Sumatra", "zh": "婆罗洲、苏门答腊", "ko": "보르네오, 수마트라"},
        "facts": ["Habitat loss is the biggest threat"],
    },

    # ---------------- Birds (12) ----------------
    "golden_eagle": {
        "name": {"en": "Golden Eagle", "zh": "金雕", "ko": "검독수리"},
        "category": "birds",
        "scientific_name": "Aquila chrysaetos",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=1200",
        "description": {
            "en": "A powerful raptor with exceptional hunting ability.",
            "zh": "北半球强大的猛禽之一，狩猎技巧高超。",
            "ko": "탁월한 사냥 능력을 지닌 강력한 맹금류.",
        },
        "characteristics": ["Huge wingspan", "Keen eyesight"],
        "habitat": {"en": "Mountains and open country", "zh": "山地与开阔地", "ko": "산지와 개활지"},
        "distribution": {"en": "Northern Hemisphere", "zh": "北半球", "ko": "북반구"},
        "facts": ["Dive speeds can be extremely high"],
    },
    "emperor_penguin": {
        "name": {"en": "Emperor Penguin", "zh": "帝企鹅", "ko": "황제펭귄"},
        "category": "birds",
        "scientific_name": "Aptenodytes forsteri",
        "conservation_status": "NT",
        "image": "https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?w=1200",
        "description": {
            "en": "The largest penguin species, breeding in Antarctic winters.",
            "zh": "体型最大的企鹅，在南极严冬繁殖。",
            "ko": "가장 큰 펭귄으로 남극의 겨울에 번식.",
        },
        "characteristics": ["Excellent diver", "Thick insulation"],
        "habitat": {"en": "Antarctic ice and surrounding seas", "zh": "南极冰架及海域", "ko": "남극 해빙과 주변 바다"},
        "distribution": {"en": "Antarctica", "zh": "南极洲", "ko": "남극"},
        "facts": ["Males incubate eggs on their feet"],
    },
    "peregrine_falcon": {
        "name": {"en": "Peregrine Falcon", "zh": "游隼", "ko": "송골매"},
        "category": "birds",
        "scientific_name": "Falco peregrinus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1604928141064-207cea6f571a?w=1200",
        "description": {
            "en": "The fastest bird in a hunting dive.",
            "zh": "俯冲速度最快的鸟类之一。",
            "ko": "사냥 급강하 시 가장 빠른 새.",
        },
        "characteristics": ["Aerial hunter", "Adaptable to cities"],
        "habitat": {"en": "Cliffs and urban high-rises", "zh": "悬崖及城市高楼", "ko": "절벽 및 도시 고층"},
        "distribution": {"en": "Worldwide", "zh": "全球分布", "ko": "전 세계"},
        "facts": ["Recovered in many regions after pesticide bans"],
    },
    "scarlet_macaw": {
        "name": {"en": "Scarlet Macaw", "zh": "红绿金刚鹦鹉", "ko": "스칼렛마코"},
        "category": "birds",
        "scientific_name": "Ara macao",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1543946207-39bd91e70ca5?w=1200",
        "description": {
            "en": "A brightly colored parrot of Central and South American rainforests.",
            "zh": "中南美热带雨林中最醒目的大型鹦鹉之一。",
            "ko": "중남미 열대우림의 화려한 대형 앵무새.",
        },
        "characteristics": ["Powerful beak", "Highly social"],
        "habitat": {"en": "Tropical rainforests", "zh": "热带雨林", "ko": "열대우림"},
        "distribution": {"en": "Central & South America", "zh": "中美洲与南美洲", "ko": "중·남아메리카"},
        "facts": ["Can mimic sounds and learn words"],
    },
    "barn_owl": {
        "name": {"en": "Barn Owl", "zh": "仓鸮", "ko": "가면올빼미"},
        "category": "birds",
        "scientific_name": "Tyto alba",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1501706362039-c6e08c1b3c3a?w=1200",
        "description": {
            "en": "A nocturnal owl with a heart-shaped face and silent flight.",
            "zh": "夜行猛禽，心形脸盘与无声飞行著称。",
            "ko": "하트 모양 얼굴과 무소음 비행이 특징인 야행성 올빼미.",
        },
        "characteristics": ["Excellent hearing", "Silent feathers"],
        "habitat": {"en": "Farmlands and open areas", "zh": "农田与开阔地", "ko": "농경지와 개활지"},
        "distribution": {"en": "Worldwide (except polar regions)", "zh": "除极地外多地分布", "ko": "극지 제외 전 세계"},
        "facts": ["Helps control rodent populations"],
    },
    "great_hornbill": {
        "name": {"en": "Great Hornbill", "zh": "大犀鸟", "ko": "큰뿔새"},
        "category": "birds",
        "scientific_name": "Buceros bicornis",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1200",
        "description": {
            "en": "A large forest bird with a prominent casque on its bill.",
            "zh": "喙上有显著盔突的大型森林鸟类。",
            "ko": "부리에 큰 볏이 있는 대형 숲새.",
        },
        "characteristics": ["Massive bill", "Important seed disperser"],
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "distribution": {"en": "South & Southeast Asia", "zh": "南亚与东南亚", "ko": "남·동남아시아"},
        "facts": ["Females may seal themselves in nest cavities"],
    },
    "wandering_albatross": {
        "name": {"en": "Wandering Albatross", "zh": "漂泊信天翁", "ko": "방랑알바트로스"},
        "category": "birds",
        "scientific_name": "Diomedea exulans",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1526336024174-2f9cb0b5a1ef?w=1200",
        "description": {
            "en": "A seabird with one of the largest wingspans of any living bird.",
            "zh": "翼展极大的远洋海鸟。",
            "ko": "현존 조류 중 가장 큰 날개폭을 가진 바닷새 중 하나.",
        },
        "characteristics": ["Efficient glider", "Long-lived"],
        "habitat": {"en": "Open Southern Ocean", "zh": "南大洋远洋", "ko": "남극해 원양"},
        "distribution": {"en": "Southern Ocean", "zh": "南大洋", "ko": "남극해"},
        "facts": ["Can fly thousands of kilometers without landing"],
    },
    "ruby_throated_hummingbird": {
        "name": {"en": "Ruby-throated Hummingbird", "zh": "红喉蜂鸟", "ko": "루비목벌새"},
        "category": "birds",
        "scientific_name": "Archilochus colubris",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=1200",
        "description": {
            "en": "A tiny bird capable of hovering and rapid wingbeats.",
            "zh": "体型小巧，可悬停飞行的蜂鸟。",
            "ko": "공중 정지가 가능한 작은 벌새.",
        },
        "characteristics": ["Feeds on nectar", "Extremely fast wingbeats"],
        "habitat": {"en": "Gardens and woodlands", "zh": "花园与林地", "ko": "정원과 숲"},
        "distribution": {"en": "Eastern North America", "zh": "北美东部", "ko": "북미 동부"},
        "facts": ["Migrates across the Gulf of Mexico"],
    },
    "greater_flamingo": {
        "name": {"en": "Greater Flamingo", "zh": "大红鹳", "ko": "큰홍학"},
        "category": "birds",
        "scientific_name": "Phoenicopterus roseus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-72c0b1b5b86b?w=1200",
        "description": {
            "en": "A tall wading bird with pink plumage from its diet.",
            "zh": "因食物导致粉色羽毛的高大涉禽。",
            "ko": "먹이로 인해 분홍빛 깃털을 띠는 큰 물새.",
        },
        "characteristics": ["Filter-feeding", "Colonial breeder"],
        "habitat": {"en": "Shallow saline lakes", "zh": "浅盐湖", "ko": "얕은 염호"},
        "distribution": {"en": "Africa, southern Europe, Asia", "zh": "非洲、南欧、亚洲", "ko": "아프리카, 남유럽, 아시아"},
        "facts": ["Chicks are born gray and turn pink later"],
    },
    "kiwi": {
        "name": {"en": "Kiwi", "zh": "几维鸟", "ko": "키위새"},
        "category": "birds",
        "scientific_name": "Apteryx spp.",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1612810436541-2b9f2b805d2e?w=1200",
        "description": {
            "en": "A flightless, nocturnal bird endemic to New Zealand.",
            "zh": "新西兰特有的夜行性不会飞的鸟。",
            "ko": "뉴질랜드 고유의 야행성 무비행 조류.",
        },
        "characteristics": ["Long bill with nostrils at tip", "Strong legs"],
        "habitat": {"en": "Forests and scrublands", "zh": "森林与灌丛", "ko": "숲과 관목지"},
        "distribution": {"en": "New Zealand", "zh": "新西兰", "ko": "뉴질랜드"},
        "facts": ["Lays an unusually large egg for its size"],
    },
    "peacock": {
        "name": {"en": "Indian Peafowl", "zh": "孔雀", "ko": "인도공작"},
        "category": "birds",
        "scientific_name": "Pavo cristatus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1200",
        "description": {
            "en": "Famous for the male’s iridescent tail display.",
            "zh": "雄鸟拥有华丽的尾屏展示。",
            "ko": "수컷의 화려한 꼬리 깃털 과시로 유명.",
        },
        "characteristics": ["Spectacular courtship display"],
        "habitat": {"en": "Open forests and farmlands", "zh": "疏林与农田", "ko": "개방 숲과 농경지"},
        "distribution": {"en": "Indian subcontinent", "zh": "印度次大陆", "ko": "인도 아대륙"},
        "facts": ["National bird of India"],
    },
    "mute_swan": {
        "name": {"en": "Mute Swan", "zh": "疣鼻天鹅", "ko": "혹부리백조"},
        "category": "birds",
        "scientific_name": "Cygnus olor",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-91c7b9b3b30c?w=1200",
        "description": {
            "en": "A large white swan known for its graceful neck curve.",
            "zh": "以优雅颈部曲线著称的大型白色天鹅。",
            "ko": "우아한 목 곡선의 큰 흰 백조.",
        },
        "characteristics": ["Territorial during breeding"],
        "habitat": {"en": "Lakes and slow rivers", "zh": "湖泊与缓流河道", "ko": "호수와 완만한 강"},
        "distribution": {"en": "Eurasia (introduced elsewhere)", "zh": "欧亚大陆（多地引入）", "ko": "유라시아 (타 지역 도입)"},
        "facts": ["Can be surprisingly aggressive when nesting"],
    },

    # ---------------- Reptiles (12) ----------------
    "nile_crocodile": {
        "name": {"en": "Nile Crocodile", "zh": "尼罗鳄", "ko": "나일악어"},
        "category": "reptiles",
        "scientific_name": "Crocodylus niloticus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?w=1200",
        "description": {
            "en": "One of Africa’s largest and most formidable crocodiles.",
            "zh": "非洲体型最大的鳄类之一。",
            "ko": "아프리카에서 가장 크고 강력한 악어 중 하나.",
        },
        "characteristics": ["Powerful bite", "Ambush predator"],
        "habitat": {"en": "Rivers, lakes, wetlands", "zh": "河流、湖泊、湿地", "ko": "강, 호수, 습지"},
        "distribution": {"en": "Sub-Saharan Africa", "zh": "撒哈拉以南非洲", "ko": "사하라 이남"},
        "facts": ["Ancient lineage dating back millions of years"],
    },
    "komodo_dragon": {
        "name": {"en": "Komodo Dragon", "zh": "科莫多巨蜥", "ko": "코모도왕도마뱀"},
        "category": "reptiles",
        "scientific_name": "Varanus komodoensis",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=1200",
        "description": {
            "en": "The world’s largest living lizard.",
            "zh": "现存最大型的蜥蜴。",
            "ko": "현존하는 가장 큰 도마뱀.",
        },
        "characteristics": ["Venom-assisted bite", "Powerful tail"],
        "habitat": {"en": "Dry forests and savannas", "zh": "干燥森林与稀树草原", "ko": "건조 숲과 사바나"},
        "distribution": {"en": "Indonesian islands (Komodo region)", "zh": "印度尼西亚科莫多群岛", "ko": "인도네시아 코모도 일대"},
        "facts": ["Can reproduce via parthenogenesis in rare cases"],
    },
    "green_sea_turtle": {
        "name": {"en": "Green Sea Turtle", "zh": "绿海龟", "ko": "푸른바다거북"},
        "category": "reptiles",
        "scientific_name": "Chelonia mydas",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1200",
        "description": {
            "en": "A large marine turtle that grazes on seagrass as an adult.",
            "zh": "成年主要食海草的大型海龟。",
            "ko": "성체가 해초를 먹는 대형 바다거북.",
        },
        "characteristics": ["Long-distance migrator"],
        "habitat": {"en": "Tropical and subtropical seas", "zh": "热带与亚热带海域", "ko": "열대·아열대 해역"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Returns to natal beaches to nest"],
    },
    "king_cobra": {
        "name": {"en": "King Cobra", "zh": "眼镜王蛇", "ko": "킹코브라"},
        "category": "reptiles",
        "scientific_name": "Ophiophagus hannah",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1585095595205-2c1f62c7f0bc?w=1200",
        "description": {
            "en": "The longest venomous snake, specializing in eating other snakes.",
            "zh": "世界上最长的毒蛇，常以其他蛇类为食。",
            "ko": "가장 긴 독사로 다른 뱀을 먹는 데 특화.",
        },
        "characteristics": ["Raises hood when threatened"],
        "habitat": {"en": "Forests and bamboo thickets", "zh": "森林与竹林", "ko": "숲과 대나무 숲"},
        "distribution": {"en": "South & Southeast Asia", "zh": "南亚与东南亚", "ko": "남·동남아시아"},
        "facts": ["Builds nests for eggs (rare among snakes)"],
    },
    "panther_chameleon": {
        "name": {"en": "Panther Chameleon", "zh": "豹纹变色龙", "ko": "팬서카멜레온"},
        "category": "reptiles",
        "scientific_name": "Furcifer pardalis",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1541417904950-b855846fe074?w=1200",
        "description": {
            "en": "A vividly colored chameleon capable of rapid color changes.",
            "zh": "色彩鲜艳、能快速变色的变色龙。",
            "ko": "선명한 색과 빠른 색 변화 능력을 지닌 카멜레온.",
        },
        "characteristics": ["Independent eye movement", "Projectile tongue"],
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "distribution": {"en": "Madagascar", "zh": "马达加斯加", "ko": "마다가스카르"},
        "facts": ["Color change reflects mood and temperature"],
    },
    "american_alligator": {
        "name": {"en": "American Alligator", "zh": "美国短吻鳄", "ko": "아메리카악어"},
        "category": "reptiles",
        "scientific_name": "Alligator mississippiensis",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1598387841680-7c9abf4c8e90?w=1200",
        "description": {
            "en": "A large reptile of the southeastern United States.",
            "zh": "美国东南部的大型鳄类。",
            "ko": "미국 남동부에 서식하는 대형 파충류.",
        },
        "characteristics": ["Broad snout", "Strong parental care"],
        "habitat": {"en": "Swamps, rivers", "zh": "沼泽、河流", "ko": "늪과 강"},
        "distribution": {"en": "Southeastern USA", "zh": "美国东南部", "ko": "미국 남동부"},
        "facts": ["Once endangered, now recovered in many areas"],
    },
    "green_anaconda": {
        "name": {"en": "Green Anaconda", "zh": "绿森蚺", "ko": "그린아나콘다"},
        "category": "reptiles",
        "scientific_name": "Eunectes murinus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1610465299993-6b2c8db05d0b?w=1200",
        "description": {
            "en": "One of the heaviest snakes, semi-aquatic.",
            "zh": "体重极大的半水栖巨蛇。",
            "ko": "가장 무거운 뱀 중 하나로 반수생.",
        },
        "characteristics": ["Constrictor", "Excellent swimmer"],
        "habitat": {"en": "Swamps and slow rivers", "zh": "沼泽与缓流河道", "ko": "늪과 완만한 강"},
        "distribution": {"en": "Amazon Basin", "zh": "亚马逊流域", "ko": "아마존 분지"},
        "facts": ["Females are much larger than males"],
    },
    "marine_iguana": {
        "name": {"en": "Marine Iguana", "zh": "海鬣蜥", "ko": "바다이구아나"},
        "category": "reptiles",
        "scientific_name": "Amblyrhynchus cristatus",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=1200",
        "description": {
            "en": "The only lizard that forages in the sea.",
            "zh": "唯一能在海中觅食的蜥蜴。",
            "ko": "바다에서 먹이를 찾는 유일한 도마뱀.",
        },
        "characteristics": ["Feeds on algae", "Flattened tail"],
        "habitat": {"en": "Rocky coasts", "zh": "岩石海岸", "ko": "바위 해안"},
        "distribution": {"en": "Galápagos Islands", "zh": "加拉帕戈斯群岛", "ko": "갈라파고스"},
        "facts": ["Can shrink in size during food shortages"],
    },
    "tokay_gecko": {
        "name": {"en": "Tokay Gecko", "zh": "大守宫", "ko": "토케이게코"},
        "category": "reptiles",
        "scientific_name": "Gekko gecko",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1604580864964-0462a5d3f3b2?w=1200",
        "description": {
            "en": "A loud-calling gecko with strong toe pads.",
            "zh": "叫声响亮、脚趾吸盘强的守宫。",
            "ko": "큰 소리로 울며 강한 발가락 흡반을 가진 게코.",
        },
        "characteristics": ["Excellent climber"],
        "habitat": {"en": "Tropical forests and buildings", "zh": "热带林与人类建筑", "ko": "열대 숲과 건물"},
        "distribution": {"en": "Southeast Asia", "zh": "东南亚", "ko": "동남아시아"},
        "facts": ["Named after its vocalization"],
    },
    "rattlesnake": {
        "name": {"en": "Rattlesnake", "zh": "响尾蛇", "ko": "방울뱀"},
        "category": "reptiles",
        "scientific_name": "Crotalus spp.",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1535083783855-0c4c3b6b8d3b?w=1200",
        "description": {
            "en": "Venomous snakes with a distinctive tail rattle warning.",
            "zh": "尾端有“响铃”用于警告的毒蛇。",
            "ko": "꼬리 방울로 경고하는 독사.",
        },
        "characteristics": ["Heat-sensing pits"],
        "habitat": {"en": "Deserts, grasslands", "zh": "沙漠与草原", "ko": "사막과 초원"},
        "distribution": {"en": "The Americas", "zh": "美洲", "ko": "아메리카"},
        "facts": ["Rattle is made of keratin segments"],
    },
    "burmese_python": {
        "name": {"en": "Burmese Python", "zh": "缅甸蟒", "ko": "버마비단뱀"},
        "category": "reptiles",
        "scientific_name": "Python bivittatus",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1610465299993-2f3e9a7fbd1a?w=1200",
        "description": {
            "en": "A large constrictor native to Southeast Asia.",
            "zh": "原产东南亚的大型缠绕性蟒蛇。",
            "ko": "동남아시아 원산의 대형 비단뱀.",
        },
        "characteristics": ["Powerful constriction"],
        "habitat": {"en": "Wetlands and forests", "zh": "湿地与森林", "ko": "습지와 숲"},
        "distribution": {"en": "Southeast Asia", "zh": "东南亚", "ko": "동남아시아"},
        "facts": ["An invasive species in parts of Florida"],
    },
    "gila_monster": {
        "name": {"en": "Gila Monster", "zh": "毒蜥", "ko": "힐라몬스터"},
        "category": "reptiles",
        "scientific_name": "Heloderma suspectum",
        "conservation_status": "NT",
        "image": "https://images.unsplash.com/photo-1541417904950-3c8dd0f2e9d0?w=1200",
        "description": {
            "en": "One of the few venomous lizards.",
            "zh": "少数具有毒性的蜥蜴之一。",
            "ko": "독을 지닌 드문 도마뱀 중 하나.",
        },
        "characteristics": ["Beaded skin texture"],
        "habitat": {"en": "Arid scrublands", "zh": "干旱灌丛", "ko": "건조 관목지"},
        "distribution": {"en": "Southwestern USA, Mexico", "zh": "美国西南与墨西哥", "ko": "미국 남서부·멕시코"},
        "facts": ["Venom inspired a diabetes drug research line"],
    },
    "chinese_water_dragon": {
        "name": {"en": "Chinese Water Dragon", "zh": "中国水龙", "ko": "중국물도마뱀"},
        "category": "reptiles",
        "scientific_name": "Physignathus cocincinus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1611078489935-7a8c5f54a1ff?w=1200",
        "description": {
            "en": "A semi-aquatic lizard with a crest, often near rivers.",
            "zh": "常见于河流附近的半水栖蜥蜴。",
            "ko": "강 주변에 사는 반수생 도마뱀.",
        },
        "characteristics": ["Good swimmer"],
        "habitat": {"en": "Riverine forests", "zh": "河谷森林", "ko": "강변 숲"},
        "distribution": {"en": "Southeast Asia", "zh": "东南亚", "ko": "동남아시아"},
        "facts": ["Can dive to escape predators"],
    },

    # ---------------- Amphibians (12) ----------------
    "red_eyed_tree_frog": {
        "name": {"en": "Red-eyed Tree Frog", "zh": "红眼树蛙", "ko": "붉은눈청개구리"},
        "category": "amphibians",
        "scientific_name": "Agalychnis callidryas",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=1200",
        "description": {
            "en": "A rainforest frog with vivid red eyes and bright green body.",
            "zh": "热带雨林中的鲜艳树蛙，以红色眼睛著称。",
            "ko": "붉은 눈과 초록 몸색이 특징인 열대우림 개구리.",
        },
        "characteristics": ["Nocturnal", "Sticky toe pads"],
        "habitat": {"en": "Tropical rainforests", "zh": "热带雨林", "ko": "열대우림"},
        "distribution": {"en": "Central America", "zh": "中美洲", "ko": "중앙아메리카"},
        "facts": ["Bright colors can startle predators"],
    },
    "axolotl": {
        "name": {"en": "Axolotl", "zh": "美西螈", "ko": "아홀로틀"},
        "category": "amphibians",
        "scientific_name": "Ambystoma mexicanum",
        "conservation_status": "CR",
        "image": "https://images.unsplash.com/photo-1602526219045-6d38787d0ed6?w=1200",
        "description": {
            "en": "A neotenic salamander famous for regeneration.",
            "zh": "以强大再生能力闻名的幼态两栖动物。",
            "ko": "재생 능력으로 유명한 유생형 도롱뇽.",
        },
        "characteristics": ["Retains larval features", "External gills"],
        "habitat": {"en": "Freshwater lakes", "zh": "淡水湖", "ko": "담수 호수"},
        "distribution": {"en": "Xochimilco (Mexico)", "zh": "墨西哥索奇米尔科", "ko": "멕시코 소치밀코"},
        "facts": ["Can regrow limbs and parts of organs"],
    },
    "poison_dart_frog": {
        "name": {"en": "Poison Dart Frog", "zh": "箭毒蛙", "ko": "독화살개구리"},
        "category": "amphibians",
        "scientific_name": "Dendrobatidae spp.",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1557050543-4d5f2e07adb2?w=1200",
        "description": {
            "en": "Small, brightly colored frogs with potent skin toxins.",
            "zh": "体型小、颜色鲜艳、皮肤含毒素的蛙类。",
            "ko": "작지만 강한 피부 독을 지닌 화려한 개구리.",
        },
        "characteristics": ["Aposematic coloration"],
        "habitat": {"en": "Tropical rainforests", "zh": "热带雨林", "ko": "열대우림"},
        "distribution": {"en": "Central & South America", "zh": "中南美洲", "ko": "중·남아메리카"},
        "facts": ["Toxins often come from diet in the wild"],
    },
    "fire_salamander": {
        "name": {"en": "Fire Salamander", "zh": "火蝾螈", "ko": "불도롱뇽"},
        "category": "amphibians",
        "scientific_name": "Salamandra salamandra",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1612810436541-9fd6f5f2a5a8?w=1200",
        "description": {
            "en": "A black-and-yellow salamander of European forests.",
            "zh": "欧洲森林中的黑黄相间蝾螈。",
            "ko": "유럽 숲의 검정-노랑 무늬 도롱뇽.",
        },
        "characteristics": ["Toxic skin secretions"],
        "habitat": {"en": "Moist forests", "zh": "潮湿森林", "ko": "습한 숲"},
        "distribution": {"en": "Europe", "zh": "欧洲", "ko": "유럽"},
        "facts": ["Warning colors signal toxicity"],
    },
    "common_toad": {
        "name": {"en": "Common Toad", "zh": "普通蟾蜍", "ko": "두꺼비"},
        "category": "amphibians",
        "scientific_name": "Bufo bufo",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-0fa0b1a2f6b7?w=1200",
        "description": {
            "en": "A widespread toad with warty skin and strong toxin glands.",
            "zh": "分布广泛、皮肤疣状、具毒腺的蟾蜍。",
            "ko": "넓게 분포하며 독샘이 있는 두꺼비.",
        },
        "characteristics": ["Terrestrial adult life"],
        "habitat": {"en": "Gardens, woodlands", "zh": "花园、林地", "ko": "정원, 숲"},
        "distribution": {"en": "Europe to Asia", "zh": "欧洲至亚洲", "ko": "유럽~아시아"},
        "facts": ["Returns to water to breed"],
    },
    "american_bullfrog": {
        "name": {"en": "American Bullfrog", "zh": "美洲牛蛙", "ko": "황소개구리"},
        "category": "amphibians",
        "scientific_name": "Lithobates catesbeianus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1564349683136-0e1b7d8d2d49?w=1200",
        "description": {
            "en": "A large frog known for its deep, bull-like call.",
            "zh": "体型大、叫声低沉的蛙类。",
            "ko": "황소 같은 울음소리로 유명한 대형 개구리.",
        },
        "characteristics": ["Large size", "Voracious appetite"],
        "habitat": {"en": "Ponds and lakes", "zh": "池塘与湖泊", "ko": "연못과 호수"},
        "distribution": {"en": "North America (introduced elsewhere)", "zh": "北美（多地引入）", "ko": "북미 (타 지역 도입)"},
        "facts": ["Can become invasive"],
    },
    "glass_frog": {
        "name": {"en": "Glass Frog", "zh": "玻璃蛙", "ko": "유리개구리"},
        "category": "amphibians",
        "scientific_name": "Centrolenidae spp.",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1557050543-8a3d0f2fdcb2?w=1200",
        "description": {
            "en": "Frogs with translucent skin showing internal organs.",
            "zh": "腹部皮肤半透明、可见内脏的蛙类。",
            "ko": "몸 일부가 반투명해 내장이 보이는 개구리.",
        },
        "characteristics": ["Arboreal", "Nocturnal"],
        "habitat": {"en": "Cloud forests near streams", "zh": "溪流附近的云雾林", "ko": "개울 인근 운무림"},
        "distribution": {"en": "Central & South America", "zh": "中南美洲", "ko": "중·남아메리카"},
        "facts": ["Males often guard egg clutches"],
    },
    "hellbender": {
        "name": {"en": "Hellbender", "zh": "地狱螈", "ko": "헬벤더"},
        "category": "amphibians",
        "scientific_name": "Cryptobranchus alleganiensis",
        "conservation_status": "NT",
        "image": "https://images.unsplash.com/photo-1602526219045-3b0b7c67c8d8?w=1200",
        "description": {
            "en": "A giant aquatic salamander of North American rivers.",
            "zh": "北美河流中的大型水栖蝾螈。",
            "ko": "북미 강에 사는 거대한 수생 도롱뇽.",
        },
        "characteristics": ["Wrinkled skin aids respiration"],
        "habitat": {"en": "Fast, oxygen-rich streams", "zh": "富氧急流", "ko": "산소가 풍부한 급류"},
        "distribution": {"en": "Eastern USA", "zh": "美国东部", "ko": "미국 동부"},
        "facts": ["Indicator of clean water"],
    },
    "wood_frog": {
        "name": {"en": "Wood Frog", "zh": "林蛙", "ko": "숲개구리"},
        "category": "amphibians",
        "scientific_name": "Lithobates sylvaticus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-fd358d3d1bd0?w=1200",
        "description": {
            "en": "A frog famous for surviving partial freezing.",
            "zh": "以能耐受部分冻结而闻名的蛙类。",
            "ko": "부분적으로 얼어도 생존하는 것으로 유명.",
        },
        "characteristics": ["Cold tolerance"],
        "habitat": {"en": "Boreal forests", "zh": "北方森林", "ko": "북방림"},
        "distribution": {"en": "North America", "zh": "北美", "ko": "북미"},
        "facts": ["Produces antifreeze-like compounds"],
    },
    "chinese_giant_salamander": {
        "name": {"en": "Chinese Giant Salamander", "zh": "中国大鲵", "ko": "중국대왕도롱뇽"},
        "category": "amphibians",
        "scientific_name": "Andrias davidianus",
        "conservation_status": "CR",
        "image": "https://images.unsplash.com/photo-1612810436541-0c2f1b1d77c7?w=1200",
        "description": {
            "en": "The world’s largest amphibian.",
            "zh": "世界上最大的两栖动物。",
            "ko": "세계에서 가장 큰 양서류.",
        },
        "characteristics": ["Aquatic", "Nocturnal"],
        "habitat": {"en": "Cool mountain streams", "zh": "山地冷水溪流", "ko": "산지 냉수 하천"},
        "distribution": {"en": "China", "zh": "中国", "ko": "중국"},
        "facts": ["Nickname: 'living fossil'"],
    },
    "chinese_fire_belly_newt": {
        "name": {"en": "Chinese Fire-bellied Newt", "zh": "中国腹火螈", "ko": "중국불배뉴트"},
        "category": "amphibians",
        "scientific_name": "Cynops orientalis",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1602526219045-0ad3c6e5a214?w=1200",
        "description": {
            "en": "A small newt with bright orange belly warning coloration.",
            "zh": "腹部橙红色的蝾螈，用于警戒捕食者。",
            "ko": "주황색 배로 경고 신호를 보내는 작은 뉴트.",
        },
        "characteristics": ["Toxic skin"],
        "habitat": {"en": "Ponds and slow streams", "zh": "池塘与缓流", "ko": "연못과 완만한 하천"},
        "distribution": {"en": "China", "zh": "中国", "ko": "중국"},
        "facts": ["Popular in aquariums"],
    },
    "caecilian": {
        "name": {"en": "Caecilian", "zh": "蚓螈（类群）", "ko": "맹장류(무족양서류)"},
        "category": "amphibians",
        "scientific_name": "Gymnophiona",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1612810436541-3c0d8f0b0e53?w=1200",
        "description": {
            "en": "Legless, burrowing amphibians that resemble worms or snakes.",
            "zh": "无足、穴居、外形类似蚯蚓或蛇的两栖动物。",
            "ko": "다리가 없고 땅속에 사는 양서류.",
        },
        "characteristics": ["Poor eyesight", "Strong burrowing ability"],
        "habitat": {"en": "Tropical soils", "zh": "热带土壤", "ko": "열대 토양"},
        "distribution": {"en": "Tropics worldwide", "zh": "全球热带地区", "ko": "전 세계 열대"},
        "facts": ["Among the least-known amphibians"],
    },

    # ---------------- Fish (12) ----------------
    "great_white_shark": {
        "name": {"en": "Great White Shark", "zh": "大白鲨", "ko": "백상아리"},
        "category": "fish",
        "scientific_name": "Carcharodon carcharias",
        "conservation_status": "VU",
        "image": "https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=1200",
        "description": {
            "en": "A large apex predator found in coastal temperate waters.",
            "zh": "温带近海的大型顶级掠食者。",
            "ko": "온대 연안의 대형 최상위 포식자.",
        },
        "characteristics": ["Powerful senses", "Multiple rows of teeth"],
        "habitat": {"en": "Coastal temperate seas", "zh": "温带近海", "ko": "온대 연안"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Rarely attacks humans compared to media image"],
    },
    "clownfish": {
        "name": {"en": "Clownfish", "zh": "小丑鱼", "ko": "흰동가리"},
        "category": "fish",
        "scientific_name": "Amphiprioninae",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1544551763-77ef2a4a6fda?w=1200",
        "description": {
            "en": "Reef fish living symbiotically with sea anemones.",
            "zh": "与海葵共生的珊瑚礁鱼类。",
            "ko": "말미잘과 공생하는 산호초 물고기.",
        },
        "characteristics": ["Protective mucus", "Social hierarchy"],
        "habitat": {"en": "Coral reefs", "zh": "珊瑚礁", "ko": "산호초"},
        "distribution": {"en": "Indo-Pacific", "zh": "印太海域", "ko": "인도-태평양"},
        "facts": ["Can change sex within a group"],
    },
    "blue_tang": {
        "name": {"en": "Blue Tang", "zh": "蓝刺尾鱼", "ko": "블루탱"},
        "category": "fish",
        "scientific_name": "Paracanthurus hepatus",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1544551763-9a7c0a11ef73?w=1200",
        "description": {
            "en": "A bright blue reef fish with a sharp tail spine.",
            "zh": "尾部有尖刺的亮蓝色珊瑚礁鱼。",
            "ko": "꼬리 가시에 독특한 밝은 파란 산호초 물고기.",
        },
        "characteristics": ["Herbivorous grazer"],
        "habitat": {"en": "Reefs", "zh": "珊瑚礁", "ko": "산호초"},
        "distribution": {"en": "Indo-Pacific", "zh": "印太海域", "ko": "인도-태평양"},
        "facts": ["Juveniles often hide among branching corals"],
    },
    "seahorse": {
        "name": {"en": "Seahorse", "zh": "海马（类群）", "ko": "해마"},
        "category": "fish",
        "scientific_name": "Hippocampus spp.",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1516685018646-549d9b6d5b12?w=1200",
        "description": {
            "en": "Fish with an upright posture and prehensile tail.",
            "zh": "直立游姿、尾巴可缠绕的奇特鱼类。",
            "ko": "직립 자세와 감기는 꼬리를 가진 물고기.",
        },
        "characteristics": ["Male pregnancy"],
        "habitat": {"en": "Seagrass beds, reefs", "zh": "海草床与礁区", "ko": "해초지와 암초"},
        "distribution": {"en": "Worldwide in shallow seas", "zh": "全球浅海", "ko": "전 세계 얕은 바다"},
        "facts": ["Males carry eggs in a brood pouch"],
    },
    "atlantic_salmon": {
        "name": {"en": "Atlantic Salmon", "zh": "大西洋鲑", "ko": "대서양연어"},
        "category": "fish",
        "scientific_name": "Salmo salar",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1516685018646-7c2f5a0bb8b5?w=1200",
        "description": {
            "en": "An anadromous fish migrating from sea to freshwater to spawn.",
            "zh": "洄游产卵的鱼类，从海洋回到淡水。",
            "ko": "바다에서 살다가 산란을 위해 민물로 올라오는 회유어.",
        },
        "characteristics": ["Strong homing instinct"],
        "habitat": {"en": "North Atlantic and rivers", "zh": "北大西洋及河流", "ko": "북대서양과 하천"},
        "distribution": {"en": "North Atlantic", "zh": "北大西洋", "ko": "북대서양"},
        "facts": ["Can leap waterfalls during migration"],
    },
    "bluefin_tuna": {
        "name": {"en": "Bluefin Tuna", "zh": "蓝鳍金枪鱼", "ko": "참다랑어"},
        "category": "fish",
        "scientific_name": "Thunnus thynnus/others",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1526336024174-c9c9f4d9dd0c?w=1200",
        "description": {
            "en": "A fast, warm-bodied tuna prized in fisheries.",
            "zh": "游速快、体温较高的金枪鱼，渔业价值高。",
            "ko": "빠르고 체온이 비교적 높은 참치류.",
        },
        "characteristics": ["Powerful swimmer"],
        "habitat": {"en": "Open ocean", "zh": "远洋", "ko": "대양"},
        "distribution": {"en": "Atlantic/Pacific depending on species", "zh": "视种类分布于大西洋/太平洋", "ko": "종에 따라 대서양/태평양"},
        "facts": ["Overfishing is a major concern"],
    },
    "manta_ray": {
        "name": {"en": "Manta Ray", "zh": "蝠鲼", "ko": "만타가오리"},
        "category": "fish",
        "scientific_name": "Mobula birostris",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1516685018646-8d0f0b5c9c8d?w=1200",
        "description": {
            "en": "A giant ray that filter-feeds on plankton.",
            "zh": "以滤食浮游生物为主的大型鳐鱼。",
            "ko": "플랑크톤을 거르는 대형 가오리.",
        },
        "characteristics": ["Intelligent, curious behavior"],
        "habitat": {"en": "Tropical oceans", "zh": "热带海洋", "ko": "열대 해역"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Often seen at cleaning stations"],
    },
    "emperor_angelfish": {
        "name": {"en": "Emperor Angelfish", "zh": "皇帝神仙鱼", "ko": "황제천사어"},
        "category": "fish",
        "scientific_name": "Pomacanthus imperator",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1544551763-1e7f0a0b1c3f?w=1200",
        "description": {
            "en": "A colorful reef fish with striking juvenile-to-adult pattern change.",
            "zh": "幼鱼与成鱼花纹差异明显的彩色珊瑚礁鱼。",
            "ko": "유어·성어 무늬가 크게 다른 화려한 산호초 어류.",
        },
        "characteristics": ["Pattern changes with age"],
        "habitat": {"en": "Coral reefs", "zh": "珊瑚礁", "ko": "산호초"},
        "distribution": {"en": "Indo-Pacific", "zh": "印太", "ko": "인도-태평양"},
        "facts": ["Juveniles help clean parasites from other fish"],
    },
    "betta": {
        "name": {"en": "Siamese Fighting Fish", "zh": "暹罗斗鱼", "ko": "베타"},
        "category": "fish",
        "scientific_name": "Betta splendens",
        "conservation_status": "VU (wild)",
        "image": "https://images.unsplash.com/photo-1526336024174-6d8e6c85f2c6?w=1200",
        "description": {
            "en": "A small labyrinth fish known for vivid colors and aggression in males.",
            "zh": "颜色艳丽、雄鱼好斗的迷鳃鱼。",
            "ko": "화려한 색과 수컷의 공격성으로 유명한 미로기관 어류.",
        },
        "characteristics": ["Can breathe air"],
        "habitat": {"en": "Slow waters, rice paddies", "zh": "缓流水域与稻田", "ko": "완만한 수역과 논"},
        "distribution": {"en": "Southeast Asia", "zh": "东南亚", "ko": "동남아시아"},
        "facts": ["Popular ornamental fish"],
    },
    "piranha": {
        "name": {"en": "Piranha", "zh": "食人鱼（类群）", "ko": "피라냐"},
        "category": "fish",
        "scientific_name": "Serrasalmidae",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1516685018646-3a0b9d5c9f6f?w=1200",
        "description": {
            "en": "Freshwater fish known for sharp teeth and group feeding.",
            "zh": "以锋利牙齿和群体觅食闻名的淡水鱼。",
            "ko": "날카로운 이빨과 무리 섭식으로 알려진 민물고기.",
        },
        "characteristics": ["Powerful bite relative to size"],
        "habitat": {"en": "Rivers and floodplains", "zh": "河流与洪泛区", "ko": "강과 범람원"},
        "distribution": {"en": "South America", "zh": "南美洲", "ko": "남아메리카"},
        "facts": ["Most species are opportunistic omnivores"],
    },
    "arapaima": {
        "name": {"en": "Arapaima", "zh": "巨骨舌鱼", "ko": "아라파이마"},
        "category": "fish",
        "scientific_name": "Arapaima gigas",
        "conservation_status": "DD",
        "image": "https://images.unsplash.com/photo-1516685018646-1a1a3a2c9d5b?w=1200",
        "description": {
            "en": "One of the largest freshwater fish, air-breathing.",
            "zh": "巨型淡水鱼，可直接呼吸空气。",
            "ko": "공기를 직접 호흡하는 거대한 민물고기.",
        },
        "characteristics": ["Armored scales"],
        "habitat": {"en": "Amazon floodplain lakes", "zh": "亚马逊洪泛湖", "ko": "아마존 범람 호수"},
        "distribution": {"en": "Amazon Basin", "zh": "亚马逊流域", "ko": "아마존 분지"},
        "facts": ["Can reach over 2 meters"],
    },
    "coelacanth": {
        "name": {"en": "Coelacanth", "zh": "腔棘鱼", "ko": "실러캔스"},
        "category": "fish",
        "scientific_name": "Latimeria chalumnae/menadoensis",
        "conservation_status": "CR",
        "image": "https://images.unsplash.com/photo-1516685018646-4a0b0f0d9b6b?w=1200",
        "description": {
            "en": "A deep-sea fish once thought extinct, often called a 'living fossil'.",
            "zh": "曾被认为已灭绝的深海鱼，被称为“活化石”。",
            "ko": "한때 멸종된 줄 알았던 심해어로 '살아있는 화석'이라 불림.",
        },
        "characteristics": ["Lobed fins"],
        "habitat": {"en": "Deep marine caves and slopes", "zh": "深海洞穴与陡坡", "ko": "심해 동굴과 경사면"},
        "distribution": {"en": "Western Indian Ocean, Indonesia", "zh": "西印度洋及印尼", "ko": "서인도양 및 인도네시아"},
        "facts": ["Has unique limb-like fin movements"],
    },

    # ---------------- Insects (12) ----------------
    "monarch_butterfly": {
        "name": {"en": "Monarch Butterfly", "zh": "帝王蝶", "ko": "제왕나비"},
        "category": "insects",
        "scientific_name": "Danaus plexippus",
        "conservation_status": "EN",
        "image": "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=1200",
        "description": {
            "en": "Famous for spectacular long-distance migration.",
            "zh": "以壮观的跨大陆迁徙闻名。",
            "ko": "장거리 이동으로 유명한 나비.",
        },
        "characteristics": ["Toxic compounds from milkweed"],
        "habitat": {"en": "Meadows and gardens", "zh": "草地与花园", "ko": "초지와 정원"},
        "distribution": {"en": "North America", "zh": "北美", "ko": "북미"},
        "facts": ["Multiple generations complete migration cycle"],
    },
    "honey_bee": {
        "name": {"en": "Honey Bee", "zh": "蜜蜂", "ko": "꿀벌"},
        "category": "insects",
        "scientific_name": "Apis mellifera",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1473973266408-ed4e6f0530c4?w=1200",
        "description": {
            "en": "A critical pollinator in natural and agricultural ecosystems.",
            "zh": "自然与农业生态系统中关键的授粉昆虫。",
            "ko": "자연·농업 생태계의 핵심 수분 곤충.",
        },
        "characteristics": ["Complex social colony"],
        "habitat": {"en": "Hives near flowering plants", "zh": "花源丰富区域", "ko": "꽃이 많은 지역"},
        "distribution": {"en": "Worldwide (managed populations)", "zh": "全球（多为饲养）", "ko": "전 세계(관리 개체군)"},
        "facts": ["Communicates via waggle dance"],
    },
    "ladybug": {
        "name": {"en": "Ladybug", "zh": "瓢虫", "ko": "무당벌레"},
        "category": "insects",
        "scientific_name": "Coccinellidae",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1465156799763-2c087c332922?w=1200",
        "description": {
            "en": "Small beetles often beneficial for controlling aphids.",
            "zh": "常用于控制蚜虫的益虫。",
            "ko": "진딧물을 먹어 해충 방제에 유익한 딱정벌레.",
        },
        "characteristics": ["Bright warning coloration"],
        "habitat": {"en": "Gardens and fields", "zh": "花园与农田", "ko": "정원과 들판"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Some species overwinter in large groups"],
    },
    "praying_mantis": {
        "name": {"en": "Praying Mantis", "zh": "螳螂", "ko": "사마귀"},
        "category": "insects",
        "scientific_name": "Mantodea",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-6b0b2c2b9f7a?w=1200",
        "description": {
            "en": "A stealthy predator with famous raptorial front legs.",
            "zh": "前足捕捉能力极强的伏击型捕食者。",
            "ko": "앞다리로 사냥하는 매복형 포식자.",
        },
        "characteristics": ["Excellent camouflage"],
        "habitat": {"en": "Shrubs and grasslands", "zh": "灌丛与草地", "ko": "관목과 초지"},
        "distribution": {"en": "Worldwide in warm regions", "zh": "温暖地区广泛分布", "ko": "따뜻한 지역 전반"},
        "facts": ["Females sometimes eat males after mating"],
    },
    "dragonfly": {
        "name": {"en": "Dragonfly", "zh": "蜻蜓", "ko": "잠자리"},
        "category": "insects",
        "scientific_name": "Odonata",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-9cf1b1b5d0f2?w=1200",
        "description": {
            "en": "Agile aerial hunters with aquatic larvae.",
            "zh": "飞行技巧高超，幼虫水生的捕食昆虫。",
            "ko": "비행이 뛰어나고 유충이 수생인 포식 곤충.",
        },
        "characteristics": ["360-degree vision"],
        "habitat": {"en": "Near freshwater", "zh": "淡水附近", "ko": "담수 인근"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Among the best insect fliers"],
    },
    "firefly": {
        "name": {"en": "Firefly", "zh": "萤火虫", "ko": "반딧불이"},
        "category": "insects",
        "scientific_name": "Lampyridae",
        "conservation_status": "Varies",
        "image": "https://images.unsplash.com/photo-1500530855697-0b0a1b2c3d4e?w=1200",
        "description": {
            "en": "Bioluminescent beetles using light signals to communicate.",
            "zh": "能发光的甲虫，用光信号交流。",
            "ko": "빛을 내어 의사소통하는 발광 딱정벌레.",
        },
        "characteristics": ["Bioluminescence"],
        "habitat": {"en": "Moist fields and forests", "zh": "潮湿草地与森林", "ko": "습한 들판·숲"},
        "distribution": {"en": "Many temperate and tropical regions", "zh": "温带与热带多地", "ko": "온대·열대 여러 지역"},
        "facts": ["Light patterns are species-specific"],
    },
    "rhinoceros_beetle": {
        "name": {"en": "Rhinoceros Beetle", "zh": "犀金龟", "ko": "장수풍뎅이"},
        "category": "insects",
        "scientific_name": "Dynastinae",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-3a9f0a1b2c3d?w=1200",
        "description": {
            "en": "Strong beetles with horn-like projections in males.",
            "zh": "雄虫有角状突起、力量惊人的甲虫。",
            "ko": "수컷의 뿔이 특징인 힘센 딱정벌레.",
        },
        "characteristics": ["Can lift many times its body weight"],
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "distribution": {"en": "Asia, Africa, Americas", "zh": "亚洲、非洲、美洲", "ko": "아시아·아프리카·아메리카"},
        "facts": ["Popular in insect-keeping cultures"],
    },
    "atlas_moth": {
        "name": {"en": "Atlas Moth", "zh": "阿特拉斯蛾", "ko": "아틀라스나방"},
        "category": "insects",
        "scientific_name": "Attacus atlas",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-7b2c2b9f7a6b?w=1200",
        "description": {
            "en": "One of the largest moths in the world.",
            "zh": "世界上最大的蛾类之一。",
            "ko": "세계에서 가장 큰 나방 중 하나.",
        },
        "characteristics": ["Huge wingspan"],
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "distribution": {"en": "South & Southeast Asia", "zh": "南亚与东南亚", "ko": "남·동남아시아"},
        "facts": ["Adults do not feed and live briefly"],
    },
    "leafcutter_ant": {
        "name": {"en": "Leafcutter Ant", "zh": "切叶蚁", "ko": "잎꾼개미"},
        "category": "insects",
        "scientific_name": "Atta spp.",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-2b9f7a6b0b1a?w=1200",
        "description": {
            "en": "Ants that cultivate fungus using collected leaves.",
            "zh": "搬运叶片种植真菌的社会性蚂蚁。",
            "ko": "잎으로 균류를 재배하는 사회성 개미.",
        },
        "characteristics": ["Fungus farming"],
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "distribution": {"en": "Central & South America", "zh": "中南美洲", "ko": "중·남아메리카"},
        "facts": ["Among the most advanced insect societies"],
    },
    "cicada": {
        "name": {"en": "Cicada", "zh": "蝉", "ko": "매미"},
        "category": "insects",
        "scientific_name": "Cicadidae",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-0b1a2b3c4d5e?w=1200",
        "description": {
            "en": "Known for loud male songs and long underground nymph stages.",
            "zh": "以雄虫鸣叫与地下若虫期较长著称。",
            "ko": "수컷의 큰 울음소리와 긴 지하 유충 시기로 유명.",
        },
        "characteristics": ["Sound-producing organs"],
        "habitat": {"en": "Trees in warm seasons", "zh": "夏季树木环境", "ko": "따뜻한 계절의 나무"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Some periodical cicadas emerge every 13 or 17 years"],
    },
    "stick_insect": {
        "name": {"en": "Stick Insect", "zh": "竹节虫", "ko": "대벌레"},
        "category": "insects",
        "scientific_name": "Phasmatodea",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-4d5e6f708192?w=1200",
        "description": {
            "en": "Masters of camouflage that mimic twigs and leaves.",
            "zh": "拟态专家，外形酷似树枝或叶片。",
            "ko": "나뭇가지나 잎을 닮는 위장 달인.",
        },
        "characteristics": ["Extreme camouflage"],
        "habitat": {"en": "Forests and shrubs", "zh": "森林与灌丛", "ko": "숲과 관목"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Some species reproduce without males"],
    },
    "dung_beetle": {
        "name": {"en": "Dung Beetle", "zh": "蜣螂", "ko": "쇠똥구리"},
        "category": "insects",
        "scientific_name": "Scarabaeinae",
        "conservation_status": "LC",
        "image": "https://images.unsplash.com/photo-1500530855697-8192a3b4c5d6?w=1200",
        "description": {
            "en": "Beetles that recycle nutrients by feeding on dung.",
            "zh": "以粪便为食、促进营养循环的甲虫。",
            "ko": "배설물을 먹어 영양 순환을 돕는 딱정벌레.",
        },
        "characteristics": ["Important decomposer"],
        "habitat": {"en": "Grasslands and savannas", "zh": "草原与稀树草原", "ko": "초원과 사바나"},
        "distribution": {"en": "Worldwide", "zh": "全球", "ko": "전 세계"},
        "facts": ["Some species navigate using the Milky Way"],
    },
}

# 根据类别获取动物列表
def get_animals_by_category(category):
    return {k: v for k, v in ANIMALS_DATA.items() if v["category"] == category}

# 获取动物详情
def get_animal_detail(animal_id):
    return ANIMALS_DATA.get(animal_id)
